# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Mod Properties
mod_id=villagersrespawn
mod_group=com.mactso.villagersrespawn
mod_version=61.1.15
archive_name = forgeVillagersRespawn

# Minecraft & Forge versions
mc_version = 1.21.11
forge_version = 61.0.5
mappings_channel=official
mappings_version=1.21.11
