# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.daemon=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.9
loader_version=0.18.3
loom_version=1.14-SNAPSHOT

# Mod Properties
	mod_version = 134.7.0
	maven_group = com.mactso.villagersrespawn
	archives_base_name = fabric-villagersrespawn-1.21.9

# Dependencies
fabric_version=0.134.0+1.21.9