modLoader="javafml"
loaderVersion="[30,)"
[[mods]]
modId="villagersrespawn"
version="${file.jarVersion}"
displayName="Villagers Respawn  Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/villagers-respawn"
updateJSONURL="https://github.com/mactso/VillagersRespawn/raw/master/update.json"
logoFile="logo.png"
authors="MacTso, Lupicus"
description='''Villagers Respawn.'''
[[dependencies.villagersrespawn]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.villagersrespawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1,1.16)"
    ordering="NONE"
    side="BOTH"
