# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
loaderVersion="[55,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]]
modId="villagersrespawn"
version="${file.jarVersion}"
displayName="Villagers Respawn  Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/villagers-respawn"
updateJSONURL="https://github.com/mactso/VillagersRespawn/raw/main/update.json"
logoFile="logo.png"
authors="MacTso, Lupicus"
description='Villagers Respawn.'
[[dependencies.villagersrespawn]]
    modId="forge"
    mandatory=true
    versionRange="[55,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.villagersrespawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.5,1.22)"
    ordering="NONE"
    side="BOTH"
