modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
[[mods]]
modId="villagersrespawn"
version="${file.jarVersion}"
displayName="Villagers Respawn  Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/villagers-respawn"
updateJSONURL="https://github.com/mactso/VillagersRespawn/raw/main/update.json"
logoFile="logo.png"
authors="MacTso, Lupicus"
description='Villagers Respawn.'
[[dependencies.villagersrespawn]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.villagersrespawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
